title: Trinity Lively
logo: "images/Trinheadshot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Student - Educator - Creator
  <br>
  Contact Info: 
  <br>
  Telephone: 918.471.7850
  Email: trinitylively@gmail.com
 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
